### ISSUE TITLE
\Doctrine\Common\Lexer\input

### ISSUE THREAD

**Issue by grzegorz-pierzakowski** [doctrine/lexer#30]
Hi,
on Line 255 there is preg_split($this->regex, $input, -1, $flags)
should be preg_split($this->regex, (string)$input, -1, $flags) due to 7.3 type casting
can you fix this, please 
Thanks

**Comment by xabbuh** [comment]
Why would that be necessary? The docblock (https://github.com/doctrine/lexer/blob/master/lib/Doctrine/Common/Lexer/AbstractLexer.php#L239) states that `$input` is a `string`.

**Comment by alcaeus** [comment]
As @xabbuh said, the docblock clearly expects a string in `setInput` which is then passed on to `scan`. Nothing has changed from the last release, so passing anything other than a string is just as invalid as it used to be. That's why we recommend using static analysers like PHPStan or psalm to ensure your code doesn't call `setInput` with anything other than a string.

**Comment by grzegorz-pierzakowski** [comment]
The doc bloc does not prevent user from calling this with a float.
Docs do not mean anything,  those are just hints.

**Comment by malarzm** [comment]
Hmmm could this happen with something like @Annotation(float=2.1)? Anyways cross referencing https://github.com/doctrine/lexer/issues/31
